package com.example.chat.event.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;

@Entity
@Table(
    name = "events",
    uniqueConstraints = @UniqueConstraint(name = "uk_session_client_event", columnNames = {"session_id", "client_event_id"})
)
@IdClass(EventId.class)
@DynamicInsert
@DynamicUpdate
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder
public class Event {

    @Id
    @Column(name = "session_id")
    private Long sessionId;

    @Id
    @Column(name = "sequence")
    private Long sequence;

    // Non-PK AUTO_INCREMENT surrogate — generated by DB on INSERT, never set by application.
    // @GeneratedValue intentionally omitted: that annotation is reserved for PK columns only.
    @Column(name = "id", unique = true, insertable = false, updatable = false)
    @Generated(event = org.hibernate.generator.EventType.INSERT)
    private Long id;

    @Column(name = "client_event_id", nullable = false, length = 64)
    private String clientEventId;

    @Column(name = "user_id", nullable = false, length = 64)
    private String userId;

    // EventType here refers to com.example.chat.event.domain.EventType (same package, no import needed).
    // org.hibernate.generator.EventType is used fully-qualified on @Generated to avoid name clash.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private EventType type;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "json", nullable = false)
    private String payload;

    @Column(name = "client_timestamp", nullable = false)
    private LocalDateTime clientTimestamp;

    @Column(name = "server_received_at", updatable = false)
    @Generated(event = org.hibernate.generator.EventType.INSERT)
    private LocalDateTime serverReceivedAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "projection_status", length = 16, insertable = false)
    @Generated(event = org.hibernate.generator.EventType.INSERT)
    private ProjectionStatus projectionStatus;

    @Column(name = "retry_count", insertable = false)
    @Generated(event = org.hibernate.generator.EventType.INSERT)
    private Integer retryCount;

    @Column(name = "next_retry_at", insertable = false)
    @Generated(event = org.hibernate.generator.EventType.INSERT)
    private LocalDateTime nextRetryAt;

    @Column(name = "last_error", length = 1024)
    private String lastError;
}
